// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Follow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UserID     uuid.UUID
	FollowedID uuid.UUID
}

type LikedPost struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UserID    uuid.UUID
	PostID    uuid.UUID
}

type Post struct {
	ID        uuid.UUID
	CreatedAt time.Time
	Content   string
	UserID    uuid.UUID
}

type User struct {
	ID           uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
	Name         string
	DisplayName  string
	Email        string
	Password     []byte
	Description  string
	Verified     bool
	Organization bool
	ApiKey       string
}
